### ISSUE TITLE
Import from Link fails.

### ISSUE THREAD

**Issue by baddog-11** [SupianIDz/HentaiCosplay#2]
Hey,
I am having problems getting the downloader to work, sadly I am not a programmer and therefore I am having some difficulties figuring out on my own what the problem is, I hope someone here can help.

First, I just downloaded the newest PHP [8.2 (8.2.4) VS16 x64 Thread Safe (2023-Mar-14 18:31:10)](https://windows.php.net/downloads/releases/php-8.2.4-nts-Win32-vs16-x64.zip) and extracted it to a new folder "Hentai" with the hentai file placed in it then I created a php.ini to enable the extensions curl, sqlite3, fileinfo and mbstring etc.
>extension=curl
extension=sqlite3
extension=fileinfo
extension=mbstring
extension=pdo_sqlite

Then I opened a cmd in that folder and wrote all commands like it says in the "Usage" Part 
The Command "php hentai app:init" created a 36,0 KB big file "database.sqlite" in C:\.hentai but the import from link command "php hentai img:crawl \*URL\*" fails every time.

To test that the extensions like sqlite3 are successfully loaded I used the command php -m afterwards to make sure everything is set up right.
![CMD window](https://i.imgur.com/mOEY9mf.png)

**Comment by SupianIDz** [comment]
Hi @baddog-11 , This has never been tested in a windows environment. I suspect it is because of the [home](https://github.com/SupianIDz/HentaiCosplay/blob/main/app/Helpers.php#L10)`difference.

At this point I'm not going to try a fix, because I don't have Windows and don't understand Windows. Maybe you can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) or [Multipass](https://multipass.run/) or Docker or anything that can install Linux easily and quickly.

If you understand how to solve this, don't hesitate to send a PR.

**Comment by SupianIDz** [comment]
@baddog-11 hi, can you send me `database.sqlite` ?

**Comment by baddog-11** [comment]
> @baddog-11 hi, can you send me `database.sqlite` ?
Here you go.
[database.zip](https://github.com/SupianIDz/HentaiCosplay/files/11008753/database.zip)

**Comment by baddog-11** [comment]
I got it working through WSL in an Ubuntu emulator.
I guess that's better than not having it work at all.

Again, Thanks for the help.

**Comment by baddog-11** [comment]
Oh, wait something went wrong after downloading the first 27 images?
![error](https://i.imgur.com/6aM9BDo.png)
